version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: customer-dashboard-nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: customer-dashboard-php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_MAX_WORKERS=${PHP_MAX_WORKERS:-10}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-}
    depends_on:
      - mysql
      - redis
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: ${PHP_MEMORY_LIMIT:-256M}
        reservations:
          cpus: '1.0'
          memory: 128M

networks:
  customer-dashboard:
