version: '3.8'

services:
  frankenphp:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    container_name: laravel-perf-frankenphp
    volumes:
      - ./:/app
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # HTTP/3 support
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - FRANKENPHP_CONFIG=worker /app/public/index.php
    depends_on:
      - mysql
      - redis
    networks:
      - laravel-perf

networks:
  laravel-perf:
    external: true
