version: '3.8'

services:
  octane:
    build:
      context: .
      dockerfile: docker/octane/Dockerfile
    container_name: laravel-perf-octane
    volumes:
      - ./:/var/www/html
    ports:
      - "80:8000"
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - laravel-perf

networks:
  laravel-perf:
    external: true
