version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: customer-dashboard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE:-laravel_perf}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: ${MYSQL_BUFFER_POOL_SIZE:-512M}
        reservations:
          cpus: '1.0'
          memory: 256M

  redis:
    image: redis:8-alpine
    container_name: customer-dashboard-redis
    command: redis-server /usr/local/etc/redis/redis.conf --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: ${REDIS_MAX_MEMORY:-256mb}
        reservations:
          cpus: '0.5'
          memory: 128M


volumes:
  mysql_data:
  redis_data:

networks:
  customer-dashboard:
    driver: bridge
