[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "app"
version = "0.1.0"
dependencies = [
    "click>=8.1",
]

[project.scripts]
app = "app.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]