groups:
  - name: laravel-performance-recording
    interval: 30s
    rules:
      - record: laravel:request_rate_5m
        expr: rate(http_requests_total[5m])
        labels:
          job: laravel-app

      - record: laravel:error_rate_5m
        expr: rate(http_requests_total{status=~"5.."}[5m])
        labels:
          job: laravel-app

      - record: laravel:response_time_p95_5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
        labels:
          job: laravel-app

      - record: mysql:query_rate_5m
        expr: rate(mysql_global_status_queries[5m])
        labels:
          job: mysql
