services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.4
    container_name: customer-dashboard-elasticsearch
    labels:
      - "com.customer-dashboard.service.type=search"
      - "com.customer-dashboard.service.roles=storage"
      - "com.customer-dashboard.service.description=Elasticsearch search and analytics engine"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - customer-dashboard

volumes:
  elasticsearch_data:

networks:
  customer-dashboard:
