services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: customer-dashboard-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
