include:
  - ./elasticsearch.yml

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.4
    container_name: customer-dashboard-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
