include:
  - ./mysql.yml

services:
  mysql-exporter:
    image: prom/mysqld-exporter:v0.15.1
    container_name: customer-dashboard-mysql-exporter
    command:
      - '--mysqld.address=mysql:3306'
      - '--mysqld.username=root'
    environment:
      - MYSQLD_EXPORTER_PASSWORD=rootpassword
    ports:
      - "9104:9104"
    depends_on:
      - mysql
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
