services:
  nginx:
    image: nginx:alpine
    container_name: customer-dashboard-nginx
    labels:
      - "com.customer-dashboard.service.type=proxy"
      - "com.customer-dashboard.service.roles=web"
      - "com.customer-dashboard.service.description=Nginx reverse proxy and web server"
    volumes:
      - ../../:/var/www/html
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M

networks:
  customer-dashboard:
