services:
  node:
    image: node:20-alpine
    container_name: customer-dashboard-node
    labels:
      - "com.customer-dashboard.service.type=build"
      - "com.customer-dashboard.service.roles=assets"
      - "com.customer-dashboard.service.description=Node.js for asset compilation and Vite dev server"
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
      - node_modules:/var/www/html/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    ports:
      - "5173:5173"
      - "3001:3001"
    command: sh -c "npm install && exec npm run dev"
    stop_signal: SIGTERM
    stop_grace_period: 10s
    networks:
      - customer-dashboard
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M

volumes:
  node_modules:
    driver: local

networks:
  customer-dashboard:
