include:
  - ./mysql.yml

services:
  proxysql:
    image: proxysql/proxysql:latest
    container_name: customer-dashboard-proxysql
    volumes:
      - ../config/proxysql/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - "6033:6033"  # MySQL protocol
      - "6032:6032"  # Admin interface
    depends_on:
      - mysql
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
