include:
  - ./redis.yml

services:
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: customer-dashboard-redis-exporter
    labels:
      - "com.customer-dashboard.service.type=monitoring"
      - "com.customer-dashboard.service.roles=metrics"
      - "com.customer-dashboard.service.description=Redis metrics exporter for Prometheus"
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
