include:
  - ./redis.yml

services:
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: customer-dashboard-redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - customer-dashboard

networks:
  customer-dashboard:
